### PR TITLE
Added Tux theme

### PR DESCRIPTION
**Pull request by josefnorlin**
Please add this since I would really like there to be a Linux Tux bootsplash.

### CODE REVIEW

**Comment by Blacksuan19** [comment]
I thought this was removed from newer kernels?

**Comment by josefnorlin** [comment]
I just created it now. Why remove Tux? He's the best symbol we have for Linux I would say.

**Comment by josefnorlin** [comment]
This is a part of a bigger attempt to bring back Tux to Linux: https://tux4ubuntu.org/

**Comment by Blacksuan19** [comment]
i am not talking about tux, tux is aight, but the bootsplash feature itself.

**Pull request merged**
